
floatRes1Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1float10.txt", header = FALSE, sep = "\t", dec = ".")
floatRes1Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1float20.txt", header = FALSE, sep = "\t", dec = ".")
floatRes1Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1float30.txt", header = FALSE, sep = "\t", dec = ".")
floatRes1Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1float40.txt", header = FALSE, sep = "\t", dec = ".")
floatRes1Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1float50.txt", header = FALSE, sep = "\t", dec = ".")
floatRes1Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1float100.txt", header = FALSE, sep = "\t", dec = ".")
floatRes1Values300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1float300.txt", header = FALSE, sep = "\t", dec = ".")
floatRes1Values500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1float500.txt", header = FALSE, sep = "\t", dec = ".")

doubleRes1Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1double10.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes1Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1double20.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes1Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1double30.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes1Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1double40.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes1Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1double50.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes1Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1double100.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes1Values300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1double300.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes1Values500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1double500.txt", header = FALSE, sep = "\t", dec = ".")

fractionRes1Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1fraction10.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes1Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1fraction20.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes1Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1fraction30.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes1Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1fraction40.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes1Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1fraction50.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes1Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1fraction100.txt", header = FALSE, sep = "\t", dec = ".")

libraryRes1Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1library10.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes1Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1library20.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes1Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1library30.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes1Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1library40.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes1Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1library50.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes1Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes1library100.txt", header = FALSE, sep = "\t", dec = ".")


floatRes2Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2float10.txt", header = FALSE, sep = "\t", dec = ".")
floatRes2Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2float20.txt", header = FALSE, sep = "\t", dec = ".")
floatRes2Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2float30.txt", header = FALSE, sep = "\t", dec = ".")
floatRes2Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2float40.txt", header = FALSE, sep = "\t", dec = ".")
floatRes2Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2float50.txt", header = FALSE, sep = "\t", dec = ".")
floatRes2Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2float100.txt", header = FALSE, sep = "\t", dec = ".")
floatRes2Values300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2float300.txt", header = FALSE, sep = "\t", dec = ".")
floatRes2Values500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2float500.txt", header = FALSE, sep = "\t", dec = ".")

doubleRes2Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2double10.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes2Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2double20.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes2Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2double30.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes2Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2double40.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes2Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2double50.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes2Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2double100.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes2Values300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2double300.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes2Values500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2double500.txt", header = FALSE, sep = "\t", dec = ".")

fractionRes2Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2fraction10.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes2Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2fraction20.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes2Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2fraction30.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes2Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2fraction40.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes2Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2fraction50.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes2Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2fraction100.txt", header = FALSE, sep = "\t", dec = ".")


libraryRes2Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2library10.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes2Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2library20.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes2Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2library30.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes2Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2library40.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes2Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2library50.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes2Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2library100.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes2Values300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2library300.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes2Values500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes2library500.txt", header = FALSE, sep = "\t", dec = ".")

floatRes3Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3float10.txt", header = FALSE, sep = "\t", dec = ".")
floatRes3Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3float20.txt", header = FALSE, sep = "\t", dec = ".")
floatRes3Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3float30.txt", header = FALSE, sep = "\t", dec = ".")
floatRes3Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3float40.txt", header = FALSE, sep = "\t", dec = ".")
floatRes3Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3float50.txt", header = FALSE, sep = "\t", dec = ".")
floatRes3Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3float100.txt", header = FALSE, sep = "\t", dec = ".")
floatRes3Values300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3float300.txt", header = FALSE, sep = "\t", dec = ".")
floatRes3Values500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3float500.txt", header = FALSE, sep = "\t", dec = ".")

doubleRes3Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3double10.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes3Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3double20.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes3Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3double30.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes3Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3double40.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes3Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3double50.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes3Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3double100.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes3Values300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3double300.txt", header = FALSE, sep = "\t", dec = ".")
doubleRes3Values500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3double500.txt", header = FALSE, sep = "\t", dec = ".")

fractionRes3Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3fraction10.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes3Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3fraction20.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes3Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3fraction30.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes3Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3fraction40.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes3Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3fraction50.txt", header = FALSE, sep = "\t", dec = ".")
fractionRes3Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3fraction100.txt", header = FALSE, sep = "\t", dec = ".")

libraryRes3Values10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3library10.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes3Values20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3library20.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes3Values30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3library30.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes3Values40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3library40.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes3Values50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3library50.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes3Values100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3library100.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes3Values300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3library300.txt", header = FALSE, sep = "\t", dec = ".")
libraryRes3Values500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matRes3library500.txt", header = FALSE, sep = "\t", dec = ".")

floatResGValues10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfloat10Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResGValues20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfloat20Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResGValues30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfloat30Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResGValues40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfloat40Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResGValues50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfloat50Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResGValues100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfloat100Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResGValues300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfloat300Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResGValues500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfloat500Gauss.txt", header = FALSE, sep = "\t", dec = ".")

doubleResGValues10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResdouble10Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResGValues20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResdouble20Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResGValues30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResdouble30Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResGValues40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResdouble40Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResGValues50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResdouble50Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResGValues100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResdouble100Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResGValues300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResdouble300Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResGValues500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResdouble500Gauss.txt", header = FALSE, sep = "\t", dec = ".")

fractionResGValues10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfraction10Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResGValues20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfraction20Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResGValues30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfraction30Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResGValues40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfraction40Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResGValues50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPResfraction50Gauss.txt", header = FALSE, sep = "\t", dec = ".")

floatResPGValues10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfloat10Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResPGValues20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfloat20Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResPGValues30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfloat30Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResPGValues40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfloat40Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResPGValues50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfloat50Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResPGValues100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfloat100Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResPGValues300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfloat300Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResPGValues500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfloat500Gauss.txt", header = FALSE, sep = "\t", dec = ".")

doubleResPGValues10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResdouble10Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResPGValues20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResdouble20Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResPGValues30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResdouble30Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResPGValues40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResdouble40Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResPGValues50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResdouble50Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResPGValues100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResdouble100Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResPGValues300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResdouble300Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResPGValues500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResdouble500Gauss.txt", header = FALSE, sep = "\t", dec = ".")

fractionResPGValues10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfraction10Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResPGValues20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfraction20Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResPGValues30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfraction30Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResPGValues40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfraction40Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResPGValues50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussPGResfraction50Gauss.txt", header = FALSE, sep = "\t", dec = ".")

floatResFGValues10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfloat10Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResFGValues20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfloat20Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResFGValues30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfloat30Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResFGValues40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfloat40Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResFGValues50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfloat50Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResFGValues100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfloat100Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResFGValues300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfloat300Gauss.txt", header = FALSE, sep = "\t", dec = ".")
floatResFGValues500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfloat500Gauss.txt", header = FALSE, sep = "\t", dec = ".")

doubleResFGValues10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResdouble10Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResFGValues20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResdouble20Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResFGValues30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResdouble30Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResFGValues40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResdouble40Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResFGValues50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResdouble50Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResFGValues100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResdouble100Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResFGValues300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResdouble300Gauss.txt", header = FALSE, sep = "\t", dec = ".")
doubleResFGValues500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResdouble500Gauss.txt", header = FALSE, sep = "\t", dec = ".")

fractionResFGValues10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfraction10Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResFGValues20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfraction20Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResFGValues30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfraction30Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResFGValues40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfraction40Gauss.txt", header = FALSE, sep = "\t", dec = ".")
fractionResFGValues50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/gaussFGResfraction50Gauss.txt", header = FALSE, sep = "\t", dec = ".")

libraryResValues10<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matResGausslibrary10Gauss.txt", header = FALSE, sep = "\t", dec = ".")
libraryResValues20<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matResGausslibrary20Gauss.txt", header = FALSE, sep = "\t", dec = ".")
libraryResValues30<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matResGausslibrary30Gauss.txt", header = FALSE, sep = "\t", dec = ".")
libraryResValues40<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matResGausslibrary40Gauss.txt", header = FALSE, sep = "\t", dec = ".")
libraryResValues50<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matResGausslibrary50Gauss.txt", header = FALSE, sep = "\t", dec = ".")
libraryResValues100<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matResGausslibrary100Gauss.txt", header = FALSE, sep = "\t", dec = ".")
libraryResValues300<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matResGausslibrary300Gauss.txt", header = FALSE, sep = "\t", dec = ".")
libraryResValues500<-read.delim("/home/mtx22/Pulpit/Algorytmy numeryczne/Algorytmy_numeryczne/Zadanie 2/results/matResGausslibrary500Gauss.txt", header = FALSE, sep = "\t", dec = ".")

# Operacje

info<-c(10,20,30,40,50,100,300,500)
floatRes1<-c(0,0,0,0,0,0,4,12)
doubleRes1<-c(0,0,0,0,0,0,4,12)
fractionRes1<-c(1,1,1,3,6,24,NA,NA)
libraryRes1<-c(11,0,0,0,0,0,18,2)

floatRes2<-c(0,1,7,7,26,221,13018,91414)
doubleRes2<-c(0,1,7,5,24,190,12771,88866)
fractionRes2<-c(4,6,8,14,35,285,NA,NA)
libraryRes2<-c(0,0,0,0,0,2,15,2)

floatRes3<-c(1,6,12,11,27,315,16202,112986)
doubleRes3<-c(1,6,14,8,27,253,19226,115314)
fractionRes3<-c(23,186,785,2875,8518,245850,NA,NA)
libraryRes3<-c(0,0,0,0,0,2,15,2)

par(mfrow=c(1,3))

plot(info,floatRes1,xlab="Rozmiar macierzy", ylab="Czas w milisekundach",type="b",main = "A * X",col="RED", pch = 19,ylim = c(0,25))
lines(info,doubleRes1,type="b",col="BLUE")
lines(info,fractionRes1,type="b",col="GREEN")
lines(info,libraryRes1,type="b")

plot(info,floatRes2,xlab="Rozmiar macierzy", ylab="Czas w milisekundach",type="b",main = "(A + B + C) * X",col="RED", pch = 19,ylim = c(0,99999))
lines(info,doubleRes2,type="b",col="BLUE")
lines(info,fractionRes2,type="b",col="GREEN")
lines(info,libraryRes2,type="b")

plot(info,floatRes3,xlab="Rozmiar macierzy", ylab="Czas w milisekundach",type="b",main = "A * (B * C)",col="RED", pch = 19,ylim = c(0,250000))
lines(info,doubleRes3,type="b",col="BLUE")
lines(info,fractionRes3,type="b",col="GREEN")
lines(info,libraryRes3,type="b")

legend("topleft", legend=c("Float", "Double", "Ułamki", "Biblioteka"),
       col=c("red", "blue","green","black"), lty = 1, cex=1)

# Gauss

info<-c(10,20,30,40,50,100,300,500)
floatResG<-c(0,1,3,7,15,13,367,2050)
doubleResG<-c(0,1,3,1,3,20,368,1890)
fractionResG<-c(13,563,6768,NA,NA,NA,NA,NA)
libraryResG<-c(5,0,0,0,1,1,22,34)

floatResPG<-c(0,1,3,6,12,45,1505,6319)
doubleResPG<-c(0,1,3,2,12,41,1604,6032)
fractionResPG<-c(12,579,7561,NA,NA,NA,NA,NA)
libraryResG<-c(5,0,0,0,1,1,22,34)

floatResFG<-c(0,1,3,6,4,49,1824,7289)
doubleResFG<-c(0,1,4,3,4,51,1915,7637)
fractionResFG<-c(12,571,7517,NA,NA,NA,NA,NA)
libraryResFG<-c(0,0,0,0,0,2,15,2)

plot(info,floatResG,xlab="Rozmiar macierzy", ylab="Czas w milisekundach",type="b",main = "Gauss bez wyboru",col="RED", pch = 19,ylim = c(0,2100))
lines(info,doubleResG,type="b",col="BLUE")
lines(info,fractionResG,type="b",col="GREEN")
lines(info,libraryResG,type="b")

plot(info,floatResPG,xlab="Rozmiar macierzy", ylab="Czas w milisekundach",type="b",main = "Gauss z wyborem częściowym",col="RED", pch = 19,ylim = c(0,6400))
lines(info,doubleResPG,type="b",col="BLUE")
lines(info,fractionResPG,type="b",col="GREEN")
lines(info,libraryResG,type="b")

plot(info,floatResFG,xlab="Rozmiar macierzy", ylab="Czas w milisekundach",type="b",main = "Gauss z pełnym częściowym",col="RED", pch = 19,ylim = c(0,7700))
lines(info,doubleResFG,type="b",col="BLUE")
lines(info,fractionResFG,type="b",col="GREEN")
lines(info,libraryResG,type="b")

calculateNormForVector<-function(vector){
  return(sum(vector))
}

